### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by Elaineok** [Jacky-Android/convnext-v2-pytorch#1]
Hi,when I run **train.py** code I get the following error：**No module named 'utils'**

**Comment by Jacky-Android** [comment]
Sorry for uploading later.

**Comment by Jacky-Android** [comment]
https://github.com/Jacky-Android/convnext-v2-pytorch/blob/main/utils.py

**Comment by Elaineok** [comment]
Thanks for the modification. 
Happy new year.
